import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

export type SocketKind = "execIn" | "execOut" | "valueIn" | "valueOut";

export interface NodeTypeSchema {
  path: string;
  execIn: number;
  execOut: number;
  valueIn: number;
  valueOut: number;
  values: string[];
  possiblyIncomplete: boolean;
  /** Exact declared field names in socket-index order - ground truth from
   * the C# source. Prefer this over `values` when you need a specific
   * socket index; `values` can diverge in length for composite widgets
   * (e.g. a single color-picker socket exploding into color_r/g/b keys). */
  valueInFields: string[];
  valueOutFields: string[];
  /** Socket kinds whose real count is defined by the Unity prefab or built at
   * runtime (array/List<> socket fields, and every "Flex" node). For these the
   * count above is a FLOOR, not a ceiling - GraphBuilder grows them on demand
   * rather than rejecting a higher index. */
  dynamicSockets?: SocketKind[];
  /** `values` came from an unreliable source heuristic rather than an observed
   * VNyan-written graph - verify the key names before relying on them. */
  valuesUncertain?: boolean;
}

interface SchemaMeta {
  unityVersion: string;
  generatedFrom: string;
  generatedBy: string;
  typeCount: number;
  valuesConfirmedFromGraphs: number;
  graphFilesScanned: number;
  note: string;
}

interface SchemaFile {
  _meta: SchemaMeta;
  types: Record<string, NodeTypeSchema>;
}

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const SCHEMA_PATH = path.join(__dirname, "schema.json");

// Generated by tools/extract-node-schema.py - see that script's docstring for
// how each field is derived and how much to trust it, and `_meta` in
// schema.json for the VNyan/Unity build it came from. Summary: socket counts
// and valueInFields/valueOutFields come from declared C# fields and are
// reliable; `values` keys are only reliable where confirmed against a real
// VNyan-written graph (otherwise `valuesUncertain` is set).
const SCHEMA_FILE: SchemaFile = JSON.parse(fs.readFileSync(SCHEMA_PATH, "utf-8"));

export function lookupNodeType(typeName: string): NodeTypeSchema | undefined {
  return SCHEMA_FILE.types[typeName];
}

export function allNodeTypes(): string[] {
  return Object.keys(SCHEMA_FILE.types).sort();
}

export function nodePath(typeName: string): string {
  return `Nodes/${typeName}`;
}

export function schemaMetadata(): SchemaMeta {
  return SCHEMA_FILE._meta;
}
